---

# pip is needed to install python modules i.e. lxml
- name: Install Pip
  apt:
    name:
      - python-pip
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

# lxml is needed to modify the jellyfin system.xml
- name: Install lxml python module
  pip:
    name: lxml

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Import Jellyfin Team GPG key
  apt_key:
    url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
    state: present
  register: apt_key_result
  retries: 3
  until: apt_key_result is succeeded

- name: Add Jellyfin repository
  apt_repository:
    repo: >
      deb https://repo.jellyfin.org/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release }} main
    state: present

- name: Install Jellyfin and {{ jellyfin_HTTP_server }}
  apt:
    update_cache: true
    name:
      - jellyfin
      - "{{ jellyfin_HTTP_server }}"
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Install jellyfin plugins
  include_tasks: plugins.yml
  when: jellyfin_plugins is defined

- name: Enable Jellyfin and {{ jellyfin_HTTP_server }}
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - jellyfin
    - "{{ jellyfin_HTTP_server }}"
...
